### ISSUE TITLE
Using refine_regularization=0. breaks jit compile in EqualityConstrainedQP

### ISSUE THREAD

**Issue by GeoffNN** [google/jaxopt#123]
```python
Traceback (most recent call last):
  File "/pscratch/sd/g/gnegiar/neural-dict-pinns/src/main.py", line 291, in <module>
    ), d_params = value_and_grad(
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/flax/linen/transforms.py", line 310, in wrapped_fn
    return trafo_fn(module_scopes, *args, **kwargs)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/flax/core/lift.py", line 201, in wrapper
    y, out_variable_groups_xs_t = fn(
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/flax/core/lift.py", line 939, in inner
    return jitted(mutable, variable_groups, rng_groups, *args)
  File "/pscratch/sd/g/gnegiar/neural-dict-pinns/src/main.py", line 220, in forward
    lam_star, dual_star = solve_QP(
  File "/pscratch/sd/g/gnegiar/neural-dict-pinns/src/qp_layer.py", line 49, in solve_QP_jaxopt
    sol_pytree = qp_layer.run(x0, (Q, c), (A, b)).params
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/implicit_diff.py", line 252, in wrapped_solver_fun
    return make_custom_vjp_solver_fun(solver_fun, keys)(*args, *vals)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/implicit_diff.py", line 206, in solver_fun_fwd
    res = solver_fun(*args, **kwargs)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/eq_qp.py", line 198, in run
    primal, dual_eq = self.solve(matvec, target, init_params,
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/linear_solve.py", line 176, in solve_gmres
    return jax.scipy.sparse.linalg.gmres(matvec, b, tol=tol, **kwargs)[0]
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jax/_src/scipy/sparse/linalg.py", line 686, in gmres
    x = lax.custom_linear_solve(A, b, solve=_solve, transpose_solve=_solve)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/linear_solve.py", line 34, in ridge_matvec
    return tree_add_scalar_mul(matvec(v), ridge, v)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/tree_util.py", line 46, in tree_add_scalar_mul
    return tree_multimap(lambda x, y: x + scalar * y, tree_x, tree_y)
  File "/global/homes/g/gnegiar/.conda/envs/neural-dict/lib/python3.9/site-packages/jaxopt/_src/tree_util.py", line 46, in <lambda>
    return tree_multimap(lambda x, y: x + scalar * y, tree_x, tree_y)
jax._src.errors.TracerIntegerConversionError: The __index__() method was called on the JAX Tracer object Traced<ShapedArray(float64[1001])>with<DynamicJaxprTrace(level=3/2)>
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError
```

**Comment by GeoffNN** [comment]
Note that this error shows up in the backward pass... I'm not sure what's going on.

**Comment by Algue-Rythme** [comment]
Nice catch !

The issue is that the `jax.scipy.sparse.linalg` API uses `A, b, x0` signature whereas the `jaxopt.linear_solve` API uses `matvec, b, ridge, init` so we cannot write code that supports both. We have to chose between the canonical Jaxopt way (with `init`), but unfortunately it is not exposed publicly... or the `jax.scipy.sparse.linalg` that the user knows about, but is incompatible... Upsettingly, neither keyword nor positional arguments can do the trick.

Hopefully in the next iterations of the library we will have a well defined API.

**Comment by GeoffNN** [comment]
One possibility could be to add a * between positional and kwargs for the jaxopt solvers? This would at least remove error ambiguity.
