### ISSUE TITLE
Retrieve init shape for solve_normal_cg

### ISSUE THREAD

**Issue by marcociccone** [google/jaxopt#232]
Hi!

I'm trying to solve a bilevel problem involving a neural network using implicit diff, but I have an incompatible shape in `solve_normal_cg` since the matrix multiplying in `matvec` is not square. 

As explained in https://github.com/google/jaxopt/issues/183, this can be solved by giving an initialization to the solver with the correct shape, but I have no clue how to find the correct shape.

Is there an automatic way to infer the shape of the initialization?
Thanks!

**Comment by marcociccone** [comment]
Tagging @froystig in case he has a solution involving `jax.eval_shape`

**Comment by mblondel** [comment]
Does it mean that you try to implement implicit diff manually yourself? Why not use `custom_root` or `custom_fixed_point`? (https://jaxopt.github.io/stable/implicit_diff.html)

**Comment by marcociccone** [comment]
Hi @mblondel, I've used `custom_root`, but I got this [exception](https://github.com/google/jaxopt/blob/20ae90b2ab46c7f4ec6905161f33b08fdc05468a/jaxopt/_src/linear_solve.py#L174-L185). 
I figured that there should be something wrong in my code because I'm not sure how I can get a non-square matrix there since `matvec` should be the `jvp` of my optimal function if I understood correctly the code. Is that correct?

I'll try to write a minimum example since my code is quite messy at the moment.

**Comment by marcociccone** [comment]
Thanks for the help, there's definitely something wrong with the optimality function and I think it's in the way I handle the auxiliary outputs.

Indeed, I prepared a simpler version of my code in [this gist](https://gist.github.com/marcociccone/8ec5d5fca363d729be7abb5243142e41) and I got a different error, but I think it's related.

I believe at this point it's a very silly error,  if you run it you get that is trying to compute the outer gradient also on the auxiliary, but I double-checked my code and all `has_aux` variables are `True`, so I don't know what the problem is.

> The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/marco/.miniconda3/lib/python3.9/site-packages/pudb/__init__.py", line 148, in runscript
    dbg._runscript(mainpyfile)
  File "/home/marco/.miniconda3/lib/python3.9/site-packages/pudb/debugger.py", line 514, in _runscript
    self.run(statement)
  File "/home/marco/.miniconda3/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "nn_ho.py", line 222, in <module>
    l2reg, outer_state = gd_outer.update(
  File "/home/marco/exp/jaxopt/jaxopt/_src/optax_wrapper.py", line 122, in update
    (value, aux), grad = self._value_and_grad_fun(params, *args, **kwargs)
TypeError: Gradient only defined for scalar-output functions. Output was (DeviceArray(2.242741, dtype=float32), FrozenDict({
    BatchNorm_0: {
        mean: DeviceArray([-2.5684078e-04, -9.7583461e-04, -3.1553689e-04,
                      1.3506041e-04, -7.3622423e-04, -4.4126890e-04,
                     -1.8133300e-04,  6.1751745e-04,  8.1947728e-06,
                     -1.8091084e-04,  3.7168273e-05, -3.4036540e-04,
                     -3.6101654e-04,  6.5738910e-05,  2.1991374e-04,
                     -1.8458175e-04, -7.1005046e-04, -3.4315197e-04,
                      2.9817550e-04, -2.1446527e-05,  6.4067350e-04,
                     -1.9983119e-04,  3.2044869e-04,  4.7262205e-04,
                     -4.9050519e-04,  6.1477134e-05,  1.4537277e-04,
                     -3.3651496e-04,  2.2027941e-04,  7.5359468e-04,
                     -1.0481578e-03, -6.8239291e-04], dtype=float32),
        var: DeviceArray([2.4596524e-05, 2.8605322e-05, 2.4403787e-05, 2.4299996e-05,
                     2.6519956e-05, 2.5262401e-05, 2.4236202e-05, 2.5503368e-05,
                     2.4063529e-05, 2.4655661e-05, 2.4135963e-05, 2.4639108e-05,
                     2.4563620e-05, 2.4611019e-05, 2.5125784e-05, 2.4883411e-05,
                     2.6458976e-05, 2.4455700e-05, 2.4919505e-05, 2.4338509e-05,
                     2.5712274e-05, 2.4678160e-05, 2.4742059e-05, 2.5531375e-05,
                     2.5158126e-05, 2.4080517e-05, 2.4277522e-05, 2.4640241e-05,
                     2.4170666e-05, 2.7325685e-05, 2.9706329e-05, 2.6279140e-05],            dtype=float32),
    },
    BatchNorm_1: {

**Comment by marcociccone** [comment]
I am able to reproduce the same error with this [code](https://gist.github.com/marcociccone/8ec5d5fca363d729be7abb5243142e41).

Do you see something wrong with the optimality function as it is?
The unrolling works correctly, but evidently I'm missing something.

Thanks

**Comment by marcociccone** [comment]
I think I figured out what the problem is. 
It seems is not enough to have `has_aux=True` in `custom_root`(which seems to be needed if the inner solver has aux).

Indeed, I think that the `vjp` [here](https://github.com/google/jaxopt/blob/60f3425f70bc6a9555cc13dcc993933dc2772c7d/jaxopt/_src/implicit_diff.py#L60) needs `has_oux=True` too, hence the exception.

I solved it by wrapping the optimality function to return only the correct output for now.
`jax.grad(lambda *args: loss_fun(*args)[0])`

Is this the intended behavior? 
I don't see the point of having an aux for the optimality function here, but it may be useful in other situations.

**Comment by mblondel** [comment]
`custom_root` with `has_aux` is tested here: https://github.com/google/jaxopt/blob/main/tests/implicit_diff_test.py#L87

If you can reproduce your issue with a smaller script and using toy data, that would be useful.

**Comment by mblondel** [comment]
I think I figured what's the confusion is. `has_aux` in `custom_root` concerns the decorated solver (https://jaxopt.github.io/stable/_autosummary/jaxopt.implicit_diff.custom_root.html#jaxopt.implicit_diff.custom_root), not `optimality_fun`, as visible from https://github.com/google/jaxopt/blob/main/tests/implicit_diff_test.py#L87.

So at the moment you need to do:
```python
def optimality_fun(params, ...):
  return jax.grad(fun, has_aux=True)(params, ...)[0]

@custom_root(optimality_fun)
def solver(init_params, ...):
   ...
  return sol
```
Maybe in the future we can add the options `optimality_fun_has_aux` and `solver_has_aux` to be more explicit... @froystig

**Comment by marcociccone** [comment]
Thanks @mblondel, that's exactly it.
I was able to make my code working.

**Comment by froystig** [comment]
Introducing explicit options sounds good to me!
