### ISSUE TITLE
Error when running Multiclass linear SVM (without intercept) example

### ISSUE THREAD

**Issue by QB3** [google/jaxopt#254]
When running the Multiclass linear SVM (without intercept) example, (https://jaxopt.github.io/stable/auto_examples/constrained/multiclass_linear_svm.html) the QP solver yields the following error:

`OSQP solution solution:
Traceback (most recent call last):
  File "multiclass_linear_svm.py", line 144, in <module>
    app.run(main)
  File "/home/qbe/anaconda3/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/qbe/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "multiclass_linear_svm.py", line 127, in main
    W_osqp = multiclass_linear_svm_osqp(X, Y, l2reg)
  File "multiclass_linear_svm.py", line 105, in multiclass_linear_svm_osqp
    init_params = osqp._box_osqp.init_params(init_x=None, **hyper_params)
  File "/home/qbe/jaxopt/jaxopt/_src/osqp.py", line 410, in init_params
    init_z = projection_box(self.matvec_A(params_eq)(init_x), params_ineq)
  File "/home/qbe/jaxopt/jaxopt/_src/osqp.py", line 47, in projection_box
    return tree_map(_clip_safe, x, lower, upper)
  File "/home/qbe/jax/jax/_src/tree_util.py", line 180, in tree_map
    all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
  File "/home/qbe/jax/jax/_src/tree_util.py", line 180, in <listcomp>
    all_leaves = [leaves] + [treedef.flatten_up_to(r) for r in rest]
ValueError: Expected list, got None.`

I guess the API of `OSQP` changed, but I did not managed to find a quick fix.

I am using the `main` branch of the developement version of  `jaxopt`

**Comment by mblondel** [comment]
Confirmed on my side. CC @Algue-Rythme
